// Code generated by protoc-gen-gogo.
// source: tags.proto
// DO NOT EDIT!

/*
Package tags is a generated protocol buffer package.

It is generated from these files:
	tags.proto

It has these top-level messages:
	Outside
	Inside
*/
package tags

import proto "github.com/maditya/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/maditya/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

type Outside struct {
	*Inside          `protobuf:"bytes,1,opt,name=Inside,json=inside,embedded=Inside" json:""`
	Field2           *string `protobuf:"bytes,2,opt,name=Field2,json=field2" json:"MyField2" xml:",comment"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Outside) Reset()                    { *m = Outside{} }
func (m *Outside) String() string            { return proto.CompactTextString(m) }
func (*Outside) ProtoMessage()               {}
func (*Outside) Descriptor() ([]byte, []int) { return fileDescriptorTags, []int{0} }

func (m *Outside) GetField2() string {
	if m != nil && m.Field2 != nil {
		return *m.Field2
	}
	return ""
}

type Inside struct {
	Field1           *string `protobuf:"bytes,1,opt,name=Field1,json=field1" json:"MyField1" xml:",chardata"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Inside) Reset()                    { *m = Inside{} }
func (m *Inside) String() string            { return proto.CompactTextString(m) }
func (*Inside) ProtoMessage()               {}
func (*Inside) Descriptor() ([]byte, []int) { return fileDescriptorTags, []int{1} }

func (m *Inside) GetField1() string {
	if m != nil && m.Field1 != nil {
		return *m.Field1
	}
	return ""
}

func init() {
	proto.RegisterType((*Outside)(nil), "tags.Outside")
	proto.RegisterType((*Inside)(nil), "tags.Inside")
}
func NewPopulatedOutside(r randyTags, easy bool) *Outside {
	this := &Outside{}
	if r.Intn(10) != 0 {
		this.Inside = NewPopulatedInside(r, easy)
	}
	if r.Intn(10) != 0 {
		v1 := randStringTags(r)
		this.Field2 = &v1
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTags(r, 3)
	}
	return this
}

func NewPopulatedInside(r randyTags, easy bool) *Inside {
	this := &Inside{}
	if r.Intn(10) != 0 {
		v2 := randStringTags(r)
		this.Field1 = &v2
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedTags(r, 2)
	}
	return this
}

type randyTags interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneTags(r randyTags) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringTags(r randyTags) string {
	v3 := r.Intn(100)
	tmps := make([]rune, v3)
	for i := 0; i < v3; i++ {
		tmps[i] = randUTF8RuneTags(r)
	}
	return string(tmps)
}
func randUnrecognizedTags(r randyTags, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldTags(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldTags(data []byte, r randyTags, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateTags(data, uint64(key))
		v4 := r.Int63()
		if r.Intn(2) == 0 {
			v4 *= -1
		}
		data = encodeVarintPopulateTags(data, uint64(v4))
	case 1:
		data = encodeVarintPopulateTags(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateTags(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateTags(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateTags(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateTags(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}

func init() { proto.RegisterFile("tags.proto", fileDescriptorTags) }

var fileDescriptorTags = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x4c, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x0c, 0xd2, 0x33, 0x4b, 0x32,
	0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x73, 0x13, 0x53, 0x32, 0x4b, 0x2a, 0x13, 0xf5, 0xc1,
	0xf2, 0x49, 0xa5, 0x69, 0xfa, 0xe9, 0xf9, 0xe9, 0xf9, 0x60, 0x0e, 0x98, 0x05, 0xd1, 0xa7, 0x54,
	0xc8, 0xc5, 0xee, 0x5f, 0x5a, 0x52, 0x9c, 0x99, 0x92, 0x2a, 0xa4, 0xc7, 0xc5, 0xe6, 0x99, 0x07,
	0x62, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xe8, 0x81, 0xcd, 0x87, 0x88, 0x39, 0x71,
	0x5c, 0xb8, 0x27, 0xcf, 0xf8, 0xea, 0x9e, 0x3c, 0x43, 0x10, 0x5b, 0x26, 0x58, 0x44, 0xc8, 0x8c,
	0x8b, 0xcd, 0x2d, 0x33, 0x35, 0x27, 0xc5, 0x48, 0x82, 0x09, 0xa8, 0x9e, 0xd3, 0x49, 0x0e, 0x28,
	0xcb, 0xe1, 0x5b, 0x09, 0x11, 0xfb, 0x74, 0x4f, 0x9e, 0xaf, 0x22, 0x37, 0xc7, 0x4a, 0x49, 0x07,
	0xe8, 0x96, 0xdc, 0xd4, 0xbc, 0x12, 0xa5, 0x20, 0xb6, 0x34, 0xb0, 0x8c, 0x92, 0x23, 0xcc, 0x1e,
	0x21, 0x73, 0xa8, 0x09, 0x86, 0x60, 0x1b, 0x39, 0x9d, 0xe4, 0x91, 0x4c, 0x30, 0x04, 0x9a, 0xc0,
	0x0f, 0x35, 0x21, 0x23, 0xb1, 0x28, 0x25, 0xb1, 0x24, 0x11, 0x66, 0x84, 0xa1, 0x13, 0xcb, 0x8f,
	0x87, 0x72, 0x8c, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x32, 0x4a, 0x66, 0x00, 0x01, 0x00,
	0x00,
}
