// Code generated by protoc-gen-gogo.
// source: combos/neither/one.proto
// DO NOT EDIT!

/*
Package one is a generated protocol buffer package.

It is generated from these files:
	combos/neither/one.proto

It has these top-level messages:
	Subby
	SampleOneOf
*/
package one

import proto "github.com/maditya/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/maditya/protobuf/gogoproto"

import github_com_maditya_protobuf_protoc_gen_gogo_descriptor "github.com/maditya/protobuf/protoc-gen-gogo/descriptor"
import github_com_maditya_protobuf_proto "github.com/maditya/protobuf/proto"
import compress_gzip "compress/gzip"
import bytes "bytes"
import io_ioutil "io/ioutil"

import strings "strings"
import sort "sort"
import strconv "strconv"
import reflect "reflect"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Subby struct {
	Sub string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
}

func (m *Subby) Reset()                    { *m = Subby{} }
func (*Subby) ProtoMessage()               {}
func (*Subby) Descriptor() ([]byte, []int) { return fileDescriptorOne, []int{0} }

type SampleOneOf struct {
	// Types that are valid to be assigned to TestOneof:
	//	*SampleOneOf_Field1
	//	*SampleOneOf_Field2
	//	*SampleOneOf_Field3
	//	*SampleOneOf_Field4
	//	*SampleOneOf_Field5
	//	*SampleOneOf_Field6
	//	*SampleOneOf_Field7
	//	*SampleOneOf_Field8
	//	*SampleOneOf_Field9
	//	*SampleOneOf_Field10
	//	*SampleOneOf_Field11
	//	*SampleOneOf_Field12
	//	*SampleOneOf_Field13
	//	*SampleOneOf_Field14
	//	*SampleOneOf_Field15
	//	*SampleOneOf_SubMessage
	TestOneof isSampleOneOf_TestOneof `protobuf_oneof:"test_oneof"`
}

func (m *SampleOneOf) Reset()                    { *m = SampleOneOf{} }
func (*SampleOneOf) ProtoMessage()               {}
func (*SampleOneOf) Descriptor() ([]byte, []int) { return fileDescriptorOne, []int{1} }

type isSampleOneOf_TestOneof interface {
	isSampleOneOf_TestOneof()
	Equal(interface{}) bool
	VerboseEqual(interface{}) error
	Size() int
}

type SampleOneOf_Field1 struct {
	Field1 float64 `protobuf:"fixed64,1,opt,name=Field1,json=field1,proto3,oneof"`
}
type SampleOneOf_Field2 struct {
	Field2 float32 `protobuf:"fixed32,2,opt,name=Field2,json=field2,proto3,oneof"`
}
type SampleOneOf_Field3 struct {
	Field3 int32 `protobuf:"varint,3,opt,name=Field3,json=field3,proto3,oneof"`
}
type SampleOneOf_Field4 struct {
	Field4 int64 `protobuf:"varint,4,opt,name=Field4,json=field4,proto3,oneof"`
}
type SampleOneOf_Field5 struct {
	Field5 uint32 `protobuf:"varint,5,opt,name=Field5,json=field5,proto3,oneof"`
}
type SampleOneOf_Field6 struct {
	Field6 uint64 `protobuf:"varint,6,opt,name=Field6,json=field6,proto3,oneof"`
}
type SampleOneOf_Field7 struct {
	Field7 int32 `protobuf:"zigzag32,7,opt,name=Field7,json=field7,proto3,oneof"`
}
type SampleOneOf_Field8 struct {
	Field8 int64 `protobuf:"zigzag64,8,opt,name=Field8,json=field8,proto3,oneof"`
}
type SampleOneOf_Field9 struct {
	Field9 uint32 `protobuf:"fixed32,9,opt,name=Field9,json=field9,proto3,oneof"`
}
type SampleOneOf_Field10 struct {
	Field10 int32 `protobuf:"fixed32,10,opt,name=Field10,json=field10,proto3,oneof"`
}
type SampleOneOf_Field11 struct {
	Field11 uint64 `protobuf:"fixed64,11,opt,name=Field11,json=field11,proto3,oneof"`
}
type SampleOneOf_Field12 struct {
	Field12 int64 `protobuf:"fixed64,12,opt,name=Field12,json=field12,proto3,oneof"`
}
type SampleOneOf_Field13 struct {
	Field13 bool `protobuf:"varint,13,opt,name=Field13,json=field13,proto3,oneof"`
}
type SampleOneOf_Field14 struct {
	Field14 string `protobuf:"bytes,14,opt,name=Field14,json=field14,proto3,oneof"`
}
type SampleOneOf_Field15 struct {
	Field15 []byte `protobuf:"bytes,15,opt,name=Field15,json=field15,proto3,oneof"`
}
type SampleOneOf_SubMessage struct {
	SubMessage *Subby `protobuf:"bytes,16,opt,name=sub_message,json=subMessage,oneof"`
}

func (*SampleOneOf_Field1) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field2) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field3) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field4) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field5) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field6) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field7) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field8) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field9) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field10) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field11) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field12) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field13) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field14) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field15) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_SubMessage) isSampleOneOf_TestOneof() {}

func (m *SampleOneOf) GetTestOneof() isSampleOneOf_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *SampleOneOf) GetField1() float64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field1); ok {
		return x.Field1
	}
	return 0
}

func (m *SampleOneOf) GetField2() float32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field2); ok {
		return x.Field2
	}
	return 0
}

func (m *SampleOneOf) GetField3() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field3); ok {
		return x.Field3
	}
	return 0
}

func (m *SampleOneOf) GetField4() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field4); ok {
		return x.Field4
	}
	return 0
}

func (m *SampleOneOf) GetField5() uint32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field5); ok {
		return x.Field5
	}
	return 0
}

func (m *SampleOneOf) GetField6() uint64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field6); ok {
		return x.Field6
	}
	return 0
}

func (m *SampleOneOf) GetField7() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field7); ok {
		return x.Field7
	}
	return 0
}

func (m *SampleOneOf) GetField8() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field8); ok {
		return x.Field8
	}
	return 0
}

func (m *SampleOneOf) GetField9() uint32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field9); ok {
		return x.Field9
	}
	return 0
}

func (m *SampleOneOf) GetField10() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field10); ok {
		return x.Field10
	}
	return 0
}

func (m *SampleOneOf) GetField11() uint64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field11); ok {
		return x.Field11
	}
	return 0
}

func (m *SampleOneOf) GetField12() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field12); ok {
		return x.Field12
	}
	return 0
}

func (m *SampleOneOf) GetField13() bool {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field13); ok {
		return x.Field13
	}
	return false
}

func (m *SampleOneOf) GetField14() string {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field14); ok {
		return x.Field14
	}
	return ""
}

func (m *SampleOneOf) GetField15() []byte {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field15); ok {
		return x.Field15
	}
	return nil
}

func (m *SampleOneOf) GetSubMessage() *Subby {
	if x, ok := m.GetTestOneof().(*SampleOneOf_SubMessage); ok {
		return x.SubMessage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SampleOneOf) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SampleOneOf_OneofMarshaler, _SampleOneOf_OneofUnmarshaler, _SampleOneOf_OneofSizer, []interface{}{
		(*SampleOneOf_Field1)(nil),
		(*SampleOneOf_Field2)(nil),
		(*SampleOneOf_Field3)(nil),
		(*SampleOneOf_Field4)(nil),
		(*SampleOneOf_Field5)(nil),
		(*SampleOneOf_Field6)(nil),
		(*SampleOneOf_Field7)(nil),
		(*SampleOneOf_Field8)(nil),
		(*SampleOneOf_Field9)(nil),
		(*SampleOneOf_Field10)(nil),
		(*SampleOneOf_Field11)(nil),
		(*SampleOneOf_Field12)(nil),
		(*SampleOneOf_Field13)(nil),
		(*SampleOneOf_Field14)(nil),
		(*SampleOneOf_Field15)(nil),
		(*SampleOneOf_SubMessage)(nil),
	}
}

func _SampleOneOf_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SampleOneOf)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *SampleOneOf_Field1:
		_ = b.EncodeVarint(1<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(math.Float64bits(x.Field1))
	case *SampleOneOf_Field2:
		_ = b.EncodeVarint(2<<3 | proto.WireFixed32)
		_ = b.EncodeFixed32(uint64(math.Float32bits(x.Field2)))
	case *SampleOneOf_Field3:
		_ = b.EncodeVarint(3<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field3))
	case *SampleOneOf_Field4:
		_ = b.EncodeVarint(4<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field4))
	case *SampleOneOf_Field5:
		_ = b.EncodeVarint(5<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field5))
	case *SampleOneOf_Field6:
		_ = b.EncodeVarint(6<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field6))
	case *SampleOneOf_Field7:
		_ = b.EncodeVarint(7<<3 | proto.WireVarint)
		_ = b.EncodeZigzag32(uint64(x.Field7))
	case *SampleOneOf_Field8:
		_ = b.EncodeVarint(8<<3 | proto.WireVarint)
		_ = b.EncodeZigzag64(uint64(x.Field8))
	case *SampleOneOf_Field9:
		_ = b.EncodeVarint(9<<3 | proto.WireFixed32)
		_ = b.EncodeFixed32(uint64(x.Field9))
	case *SampleOneOf_Field10:
		_ = b.EncodeVarint(10<<3 | proto.WireFixed32)
		_ = b.EncodeFixed32(uint64(x.Field10))
	case *SampleOneOf_Field11:
		_ = b.EncodeVarint(11<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(uint64(x.Field11))
	case *SampleOneOf_Field12:
		_ = b.EncodeVarint(12<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(uint64(x.Field12))
	case *SampleOneOf_Field13:
		t := uint64(0)
		if x.Field13 {
			t = 1
		}
		_ = b.EncodeVarint(13<<3 | proto.WireVarint)
		_ = b.EncodeVarint(t)
	case *SampleOneOf_Field14:
		_ = b.EncodeVarint(14<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Field14)
	case *SampleOneOf_Field15:
		_ = b.EncodeVarint(15<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Field15)
	case *SampleOneOf_SubMessage:
		_ = b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SubMessage); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SampleOneOf.TestOneof has unexpected type %T", x)
	}
	return nil
}

func _SampleOneOf_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SampleOneOf)
	switch tag {
	case 1: // test_oneof.Field1
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestOneof = &SampleOneOf_Field1{math.Float64frombits(x)}
		return true, err
	case 2: // test_oneof.Field2
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.TestOneof = &SampleOneOf_Field2{math.Float32frombits(uint32(x))}
		return true, err
	case 3: // test_oneof.Field3
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field3{int32(x)}
		return true, err
	case 4: // test_oneof.Field4
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field4{int64(x)}
		return true, err
	case 5: // test_oneof.Field5
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field5{uint32(x)}
		return true, err
	case 6: // test_oneof.Field6
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field6{x}
		return true, err
	case 7: // test_oneof.Field7
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag32()
		m.TestOneof = &SampleOneOf_Field7{int32(x)}
		return true, err
	case 8: // test_oneof.Field8
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag64()
		m.TestOneof = &SampleOneOf_Field8{int64(x)}
		return true, err
	case 9: // test_oneof.Field9
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.TestOneof = &SampleOneOf_Field9{uint32(x)}
		return true, err
	case 10: // test_oneof.Field10
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.TestOneof = &SampleOneOf_Field10{int32(x)}
		return true, err
	case 11: // test_oneof.Field11
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestOneof = &SampleOneOf_Field11{x}
		return true, err
	case 12: // test_oneof.Field12
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestOneof = &SampleOneOf_Field12{int64(x)}
		return true, err
	case 13: // test_oneof.Field13
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field13{x != 0}
		return true, err
	case 14: // test_oneof.Field14
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestOneof = &SampleOneOf_Field14{x}
		return true, err
	case 15: // test_oneof.Field15
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.TestOneof = &SampleOneOf_Field15{x}
		return true, err
	case 16: // test_oneof.sub_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Subby)
		err := b.DecodeMessage(msg)
		m.TestOneof = &SampleOneOf_SubMessage{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SampleOneOf_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SampleOneOf)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *SampleOneOf_Field1:
		n += proto.SizeVarint(1<<3 | proto.WireFixed64)
		n += 8
	case *SampleOneOf_Field2:
		n += proto.SizeVarint(2<<3 | proto.WireFixed32)
		n += 4
	case *SampleOneOf_Field3:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field3))
	case *SampleOneOf_Field4:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field4))
	case *SampleOneOf_Field5:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field5))
	case *SampleOneOf_Field6:
		n += proto.SizeVarint(6<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field6))
	case *SampleOneOf_Field7:
		n += proto.SizeVarint(7<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64((uint32(x.Field7) << 1) ^ uint32((int32(x.Field7) >> 31))))
	case *SampleOneOf_Field8:
		n += proto.SizeVarint(8<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(uint64(x.Field8<<1) ^ uint64((int64(x.Field8) >> 63))))
	case *SampleOneOf_Field9:
		n += proto.SizeVarint(9<<3 | proto.WireFixed32)
		n += 4
	case *SampleOneOf_Field10:
		n += proto.SizeVarint(10<<3 | proto.WireFixed32)
		n += 4
	case *SampleOneOf_Field11:
		n += proto.SizeVarint(11<<3 | proto.WireFixed64)
		n += 8
	case *SampleOneOf_Field12:
		n += proto.SizeVarint(12<<3 | proto.WireFixed64)
		n += 8
	case *SampleOneOf_Field13:
		n += proto.SizeVarint(13<<3 | proto.WireVarint)
		n += 1
	case *SampleOneOf_Field14:
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Field14)))
		n += len(x.Field14)
	case *SampleOneOf_Field15:
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Field15)))
		n += len(x.Field15)
	case *SampleOneOf_SubMessage:
		s := proto.Size(x.SubMessage)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Subby)(nil), "one.Subby")
	proto.RegisterType((*SampleOneOf)(nil), "one.SampleOneOf")
}
func (this *Subby) Description() (desc *github_com_maditya_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	return OneDescription()
}
func (this *SampleOneOf) Description() (desc *github_com_maditya_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	return OneDescription()
}
func OneDescription() (desc *github_com_maditya_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	d := &github_com_maditya_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet{}
	var gzipped = []byte{
		// 3593 bytes of a gzipped FileDescriptorSet
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x5a, 0x5d, 0x6c, 0x23, 0xd7,
		0x75, 0xd6, 0xf0, 0x4f, 0xe4, 0x21, 0x45, 0x8d, 0xae, 0xe4, 0xf5, 0xac, 0x6c, 0x73, 0xb5, 0xb2,
		0x1d, 0xcb, 0x76, 0xa3, 0xdd, 0xd5, 0x4a, 0xfb, 0xc3, 0x6d, 0x62, 0x50, 0x12, 0xad, 0x95, 0x21,
		0x89, 0xea, 0x50, 0x4a, 0xd6, 0xe9, 0xc3, 0x60, 0x38, 0xbc, 0xa4, 0x66, 0x77, 0x38, 0xc3, 0xce,
		0x0c, 0xd7, 0x96, 0x9f, 0xb6, 0x70, 0x7f, 0x10, 0x14, 0xfd, 0x2f, 0xd0, 0xd8, 0x71, 0xd2, 0x36,
		0x68, 0xeb, 0x34, 0xfd, 0x4b, 0xfa, 0x87, 0xa2, 0x4f, 0x05, 0x8a, 0xb4, 0x79, 0x2a, 0xd2, 0x3e,
		0xf5, 0x21, 0x0f, 0x59, 0xd5, 0x40, 0xd3, 0x36, 0x6d, 0x5d, 0x60, 0x81, 0x06, 0xf0, 0x4b, 0x71,
		0xff, 0x66, 0x86, 0x3f, 0xda, 0xa1, 0x02, 0xa4, 0xe9, 0x93, 0x34, 0xe7, 0x9c, 0xef, 0x9b, 0x7b,
		0xcf, 0x3d, 0xf7, 0x9c, 0x73, 0xef, 0x10, 0xfe, 0xe6, 0x0a, 0x2c, 0xb4, 0x1d, 0xa7, 0x6d, 0xe1,
		0x4b, 0x5d, 0xd7, 0xf1, 0x9d, 0x46, 0xaf, 0x75, 0xa9, 0x89, 0x3d, 0xc3, 0x35, 0xbb, 0xbe, 0xe3,
		0x2e, 0x53, 0x19, 0x9a, 0x66, 0x16, 0xcb, 0xc2, 0x62, 0x71, 0x17, 0x66, 0x5e, 0x35, 0x2d, 0xbc,
		0x19, 0x18, 0xd6, 0xb1, 0x8f, 0x6e, 0x40, 0xaa, 0x65, 0x5a, 0x58, 0x91, 0x16, 0x92, 0x4b, 0xf9,
		0x95, 0xe7, 0x96, 0x07, 0x40, 0xcb, 0xfd, 0x88, 0x7d, 0x22, 0x56, 0x29, 0x62, 0xf1, 0x83, 0x14,
		0xcc, 0x8e, 0xd0, 0x22, 0x04, 0x29, 0x5b, 0xef, 0x10, 0x46, 0x69, 0x29, 0xa7, 0xd2, 0xff, 0x91,
		0x02, 0x93, 0x5d, 0xdd, 0xb8, 0xa7, 0xb7, 0xb1, 0x92, 0xa0, 0x62, 0xf1, 0x88, 0x4a, 0x00, 0x4d,
		0xdc, 0xc5, 0x76, 0x13, 0xdb, 0xc6, 0xb1, 0x92, 0x5c, 0x48, 0x2e, 0xe5, 0xd4, 0x88, 0x04, 0xbd,
		0x0c, 0x33, 0xdd, 0x5e, 0xc3, 0x32, 0x0d, 0x2d, 0x62, 0x06, 0x0b, 0xc9, 0xa5, 0xb4, 0x2a, 0x33,
		0xc5, 0x66, 0x68, 0xfc, 0x02, 0x4c, 0xbf, 0x81, 0xf5, 0x7b, 0x51, 0xd3, 0x3c, 0x35, 0x2d, 0x12,
		0x71, 0xc4, 0x70, 0x03, 0x0a, 0x1d, 0xec, 0x79, 0x7a, 0x1b, 0x6b, 0xfe, 0x71, 0x17, 0x2b, 0x29,
		0x3a, 0xfb, 0x85, 0xa1, 0xd9, 0x0f, 0xce, 0x3c, 0xcf, 0x51, 0x07, 0xc7, 0x5d, 0x8c, 0x2a, 0x90,
		0xc3, 0x76, 0xaf, 0xc3, 0x18, 0xd2, 0xa7, 0xf8, 0xaf, 0x6a, 0xf7, 0x3a, 0x83, 0x2c, 0x59, 0x02,
		0xe3, 0x14, 0x93, 0x1e, 0x76, 0xef, 0x9b, 0x06, 0x56, 0x32, 0x94, 0xe0, 0x85, 0x21, 0x82, 0x3a,
		0xd3, 0x0f, 0x72, 0x08, 0x1c, 0xda, 0x80, 0x1c, 0x7e, 0xd3, 0xc7, 0xb6, 0x67, 0x3a, 0xb6, 0x32,
		0x49, 0x49, 0x9e, 0x1f, 0xb1, 0x8a, 0xd8, 0x6a, 0x0e, 0x52, 0x84, 0x38, 0x74, 0x0d, 0x26, 0x9d,
		0xae, 0x6f, 0x3a, 0xb6, 0xa7, 0x64, 0x17, 0xa4, 0xa5, 0xfc, 0xca, 0xd3, 0x23, 0x03, 0xa1, 0xc6,
		0x6c, 0x54, 0x61, 0x8c, 0xb6, 0x41, 0xf6, 0x9c, 0x9e, 0x6b, 0x60, 0xcd, 0x70, 0x9a, 0x58, 0x33,
		0xed, 0x96, 0xa3, 0xe4, 0x28, 0xc1, 0x85, 0xe1, 0x89, 0x50, 0xc3, 0x0d, 0xa7, 0x89, 0xb7, 0xed,
		0x96, 0xa3, 0x16, 0xbd, 0xbe, 0x67, 0x74, 0x0e, 0x32, 0xde, 0xb1, 0xed, 0xeb, 0x6f, 0x2a, 0x05,
		0x1a, 0x21, 0xfc, 0x69, 0xf1, 0x7f, 0xd2, 0x30, 0x3d, 0x4e, 0x88, 0xdd, 0x82, 0x74, 0x8b, 0xcc,
		0x52, 0x49, 0x9c, 0xc5, 0x07, 0x0c, 0xd3, 0xef, 0xc4, 0xcc, 0xf7, 0xe9, 0xc4, 0x0a, 0xe4, 0x6d,
		0xec, 0xf9, 0xb8, 0xc9, 0x22, 0x22, 0x39, 0x66, 0x4c, 0x01, 0x03, 0x0d, 0x87, 0x54, 0xea, 0xfb,
		0x0a, 0xa9, 0x3b, 0x30, 0x1d, 0x0c, 0x49, 0x73, 0x75, 0xbb, 0x2d, 0x62, 0xf3, 0x52, 0xdc, 0x48,
		0x96, 0xab, 0x02, 0xa7, 0x12, 0x98, 0x5a, 0xc4, 0x7d, 0xcf, 0x68, 0x13, 0xc0, 0xb1, 0xb1, 0xd3,
		0xd2, 0x9a, 0xd8, 0xb0, 0x94, 0xec, 0x29, 0x5e, 0xaa, 0x11, 0x93, 0x21, 0x2f, 0x39, 0x4c, 0x6a,
		0x58, 0xe8, 0x66, 0x18, 0x6a, 0x93, 0xa7, 0x44, 0xca, 0x2e, 0xdb, 0x64, 0x43, 0xd1, 0x76, 0x08,
		0x45, 0x17, 0x93, 0xb8, 0xc7, 0x4d, 0x3e, 0xb3, 0x1c, 0x1d, 0xc4, 0x72, 0xec, 0xcc, 0x54, 0x0e,
		0x63, 0x13, 0x9b, 0x72, 0xa3, 0x8f, 0xe8, 0x59, 0x08, 0x04, 0x1a, 0x0d, 0x2b, 0xa0, 0x59, 0xa8,
		0x20, 0x84, 0x7b, 0x7a, 0x07, 0xcf, 0xdf, 0x80, 0x62, 0xbf, 0x7b, 0xd0, 0x1c, 0xa4, 0x3d, 0x5f,
		0x77, 0x7d, 0x1a, 0x85, 0x69, 0x95, 0x3d, 0x20, 0x19, 0x92, 0xd8, 0x6e, 0xd2, 0x2c, 0x97, 0x56,
		0xc9, 0xbf, 0xf3, 0xd7, 0x61, 0xaa, 0xef, 0xf5, 0xe3, 0x02, 0x17, 0x3f, 0x97, 0x81, 0xb9, 0x51,
		0x31, 0x37, 0x32, 0xfc, 0xcf, 0x41, 0xc6, 0xee, 0x75, 0x1a, 0xd8, 0x55, 0x92, 0x94, 0x81, 0x3f,
		0xa1, 0x0a, 0xa4, 0x2d, 0xbd, 0x81, 0x2d, 0x25, 0xb5, 0x20, 0x2d, 0x15, 0x57, 0x5e, 0x1e, 0x2b,
		0xaa, 0x97, 0x77, 0x08, 0x44, 0x65, 0x48, 0xf4, 0x49, 0x48, 0xf1, 0x14, 0x47, 0x18, 0x5e, 0x1a,
		0x8f, 0x81, 0xc4, 0xa2, 0x4a, 0x71, 0xe8, 0x29, 0xc8, 0x91, 0xbf, 0xcc, 0xb7, 0x19, 0x3a, 0xe6,
		0x2c, 0x11, 0x10, 0xbf, 0xa2, 0x79, 0xc8, 0xd2, 0x30, 0x6b, 0x62, 0x51, 0x1a, 0x82, 0x67, 0xb2,
		0x30, 0x4d, 0xdc, 0xd2, 0x7b, 0x96, 0xaf, 0xdd, 0xd7, 0xad, 0x1e, 0xa6, 0x01, 0x93, 0x53, 0x0b,
		0x5c, 0xf8, 0x29, 0x22, 0x43, 0x17, 0x20, 0xcf, 0xa2, 0xd2, 0xb4, 0x9b, 0xf8, 0x4d, 0x9a, 0x7d,
		0xd2, 0x2a, 0x0b, 0xd4, 0x6d, 0x22, 0x21, 0xaf, 0xbf, 0xeb, 0x39, 0xb6, 0x58, 0x5a, 0xfa, 0x0a,
		0x22, 0xa0, 0xaf, 0xbf, 0x3e, 0x98, 0xf8, 0x9e, 0x19, 0x3d, 0xbd, 0xc1, 0x58, 0x5c, 0xfc, 0x8b,
		0x04, 0xa4, 0xe8, 0x7e, 0x9b, 0x86, 0xfc, 0xc1, 0xeb, 0xfb, 0x55, 0x6d, 0xb3, 0x76, 0xb8, 0xbe,
		0x53, 0x95, 0x25, 0x54, 0x04, 0xa0, 0x82, 0x57, 0x77, 0x6a, 0x95, 0x03, 0x39, 0x11, 0x3c, 0x6f,
		0xef, 0x1d, 0x5c, 0x5b, 0x95, 0x93, 0x01, 0xe0, 0x90, 0x09, 0x52, 0x51, 0x83, 0xab, 0x2b, 0x72,
		0x1a, 0xc9, 0x50, 0x60, 0x04, 0xdb, 0x77, 0xaa, 0x9b, 0xd7, 0x56, 0xe5, 0x4c, 0xbf, 0xe4, 0xea,
		0x8a, 0x3c, 0x89, 0xa6, 0x20, 0x47, 0x25, 0xeb, 0xb5, 0xda, 0x8e, 0x9c, 0x0d, 0x38, 0xeb, 0x07,
		0xea, 0xf6, 0xde, 0x96, 0x9c, 0x0b, 0x38, 0xb7, 0xd4, 0xda, 0xe1, 0xbe, 0x0c, 0x01, 0xc3, 0x6e,
		0xb5, 0x5e, 0xaf, 0x6c, 0x55, 0xe5, 0x7c, 0x60, 0xb1, 0xfe, 0xfa, 0x41, 0xb5, 0x2e, 0x17, 0xfa,
		0x86, 0x75, 0x75, 0x45, 0x9e, 0x0a, 0x5e, 0x51, 0xdd, 0x3b, 0xdc, 0x95, 0x8b, 0x68, 0x06, 0xa6,
		0xd8, 0x2b, 0xc4, 0x20, 0xa6, 0x07, 0x44, 0xd7, 0x56, 0x65, 0x39, 0x1c, 0x08, 0x63, 0x99, 0xe9,
		0x13, 0x5c, 0x5b, 0x95, 0xd1, 0xe2, 0x06, 0xa4, 0x69, 0x74, 0x21, 0x04, 0xc5, 0x9d, 0xca, 0x7a,
		0x75, 0x47, 0xab, 0xed, 0x1f, 0x6c, 0xd7, 0xf6, 0x2a, 0x3b, 0xb2, 0x14, 0xca, 0xd4, 0xea, 0x8f,
		0x1d, 0x6e, 0xab, 0xd5, 0x4d, 0x39, 0x11, 0x95, 0xed, 0x57, 0x2b, 0x07, 0xd5, 0x4d, 0x39, 0xb9,
		0xf8, 0x12, 0xcc, 0x8d, 0xca, 0x33, 0xa3, 0x76, 0xc6, 0xe2, 0x97, 0x24, 0x98, 0x1d, 0x91, 0x32,
		0x47, 0xee, 0xa2, 0x57, 0x20, 0xcd, 0x22, 0x8d, 0x15, 0x91, 0x17, 0x47, 0xe6, 0x5e, 0x1a, 0x77,
		0x43, 0x85, 0x84, 0xe2, 0xa2, 0x85, 0x34, 0x79, 0x4a, 0x21, 0x25, 0x14, 0x43, 0xe1, 0xf4, 0xb6,
		0x04, 0xca, 0x69, 0xdc, 0x31, 0xfb, 0x3d, 0xd1, 0xb7, 0xdf, 0x6f, 0x0d, 0x0e, 0xe0, 0xe2, 0xe9,
		0x73, 0x18, 0x1a, 0xc5, 0xfb, 0x12, 0x9c, 0x1b, 0xdd, 0x6f, 0x8c, 0x1c, 0xc3, 0x27, 0x21, 0xd3,
		0xc1, 0xfe, 0x91, 0x23, 0x6a, 0xee, 0xc7, 0x46, 0x64, 0x72, 0xa2, 0x1e, 0xf4, 0x15, 0x47, 0x45,
		0x4b, 0x41, 0xf2, 0xb4, 0xa6, 0x81, 0x8d, 0x66, 0x68, 0xa4, 0x9f, 0x4d, 0xc0, 0x13, 0x23, 0xc9,
		0x47, 0x0e, 0xf4, 0x19, 0x00, 0xd3, 0xee, 0xf6, 0x7c, 0x56, 0x57, 0x59, 0x9a, 0xc9, 0x51, 0x09,
		0xdd, 0xc2, 0x24, 0x85, 0xf4, 0xfc, 0x40, 0x9f, 0xa4, 0x7a, 0x60, 0x22, 0x6a, 0x70, 0x23, 0x1c,
		0x68, 0x8a, 0x0e, 0xb4, 0x74, 0xca, 0x4c, 0x87, 0x4a, 0xd6, 0x65, 0x90, 0x0d, 0xcb, 0xc4, 0xb6,
		0xaf, 0x79, 0xbe, 0x8b, 0xf5, 0x8e, 0x69, 0xb7, 0x69, 0x1e, 0xcd, 0x96, 0xd3, 0x2d, 0xdd, 0xf2,
		0xb0, 0x3a, 0xcd, 0xd4, 0x75, 0xa1, 0x25, 0x08, 0x5a, 0x2c, 0xdc, 0x08, 0x22, 0xd3, 0x87, 0x60,
		0xea, 0x00, 0xb1, 0xf8, 0x8f, 0x93, 0x90, 0x8f, 0x74, 0x67, 0xe8, 0x22, 0x14, 0xee, 0xea, 0xf7,
		0x75, 0x4d, 0x74, 0xdc, 0xcc, 0x13, 0x79, 0x22, 0xdb, 0xe7, 0x5d, 0xf7, 0x65, 0x98, 0xa3, 0x26,
		0x4e, 0xcf, 0xc7, 0xae, 0x66, 0x58, 0xba, 0xe7, 0x51, 0xa7, 0x65, 0xa9, 0x29, 0x22, 0xba, 0x1a,
		0x51, 0x6d, 0x08, 0x0d, 0x5a, 0x83, 0x59, 0x8a, 0xe8, 0xf4, 0x2c, 0xdf, 0xec, 0x5a, 0x58, 0x23,
		0x67, 0x00, 0x8f, 0xe6, 0xd3, 0x60, 0x64, 0x33, 0xc4, 0x62, 0x97, 0x1b, 0x90, 0x11, 0x79, 0x68,
		0x0b, 0x9e, 0xa1, 0xb0, 0x36, 0xb6, 0xb1, 0xab, 0xfb, 0x58, 0xc3, 0x3f, 0xd1, 0xd3, 0x2d, 0x4f,
		0xd3, 0xed, 0xa6, 0x76, 0xa4, 0x7b, 0x47, 0xca, 0x5c, 0x94, 0xe0, 0x3c, 0xb1, 0xdd, 0xe2, 0xa6,
		0x55, 0x6a, 0x59, 0xb1, 0x9b, 0xb7, 0x75, 0xef, 0x08, 0x95, 0xe1, 0x1c, 0x25, 0xf2, 0x7c, 0xd7,
		0xb4, 0xdb, 0x9a, 0x71, 0x84, 0x8d, 0x7b, 0x5a, 0xcf, 0x6f, 0xdd, 0x50, 0x9e, 0x8a, 0x32, 0xd0,
		0x41, 0xd6, 0xa9, 0xcd, 0x06, 0x31, 0x39, 0xf4, 0x5b, 0x37, 0x50, 0x1d, 0x0a, 0x64, 0x3d, 0x3a,
		0xe6, 0x5b, 0x58, 0x6b, 0x39, 0x2e, 0xad, 0x11, 0xc5, 0x11, 0x9b, 0x3b, 0xe2, 0xc4, 0xe5, 0x1a,
		0x07, 0xec, 0x3a, 0x4d, 0x5c, 0x4e, 0xd7, 0xf7, 0xab, 0xd5, 0x4d, 0x35, 0x2f, 0x58, 0x5e, 0x75,
		0x5c, 0x12, 0x53, 0x6d, 0x27, 0xf0, 0x71, 0x9e, 0xc5, 0x54, 0xdb, 0x11, 0x1e, 0x5e, 0x83, 0x59,
		0xc3, 0x60, 0xd3, 0x36, 0x0d, 0x8d, 0x37, 0xeb, 0x9e, 0x22, 0xf7, 0xf9, 0xcb, 0x30, 0xb6, 0x98,
		0x01, 0x0f, 0x73, 0x0f, 0xdd, 0x84, 0x27, 0x42, 0x7f, 0x45, 0x81, 0x33, 0x43, 0xb3, 0x1c, 0x84,
		0xae, 0xc1, 0x6c, 0xf7, 0x78, 0x18, 0x88, 0xfa, 0xde, 0xd8, 0x3d, 0x1e, 0x84, 0x3d, 0x4f, 0x0f,
		0x60, 0x2e, 0x36, 0x74, 0x1f, 0x37, 0x95, 0x27, 0xa3, 0xd6, 0x11, 0x05, 0xba, 0x04, 0xb2, 0x61,
		0x68, 0xd8, 0xd6, 0x1b, 0x16, 0xd6, 0x74, 0x17, 0xdb, 0xba, 0xa7, 0x5c, 0x88, 0x1a, 0x17, 0x0d,
		0xa3, 0x4a, 0xb5, 0x15, 0xaa, 0x44, 0x2f, 0xc1, 0x8c, 0xd3, 0xb8, 0x6b, 0xb0, 0xe0, 0xd2, 0xba,
		0x2e, 0x6e, 0x99, 0x6f, 0x2a, 0xcf, 0x51, 0x37, 0x4d, 0x13, 0x05, 0x0d, 0xad, 0x7d, 0x2a, 0x46,
		0x2f, 0x82, 0x6c, 0x78, 0x47, 0xba, 0xdb, 0xa5, 0x45, 0xda, 0xeb, 0xea, 0x06, 0x56, 0x9e, 0x67,
		0xa6, 0x4c, 0xbe, 0x27, 0xc4, 0xa8, 0x0a, 0x17, 0xc8, 0xe4, 0x6d, 0xdd, 0x76, 0xb4, 0x9e, 0x87,
		0xb5, 0x70, 0x88, 0xc1, 0x5a, 0x7c, 0x8c, 0x0c, 0x4b, 0x7d, 0x5a, 0x98, 0x1d, 0x7a, 0x78, 0x33,
		0x30, 0x12, 0xcb, 0x73, 0x07, 0xe6, 0x7a, 0xb6, 0x69, 0xfb, 0xd8, 0xed, 0xba, 0x98, 0x80, 0xd9,
		0x86, 0x55, 0xfe, 0x65, 0xf2, 0x94, 0xa6, 0xfb, 0x30, 0x6a, 0xcd, 0x82, 0x44, 0x9d, 0xed, 0x0d,
		0x0b, 0x17, 0xcb, 0x50, 0x88, 0xc6, 0x0e, 0xca, 0x01, 0x8b, 0x1e, 0x59, 0x22, 0x15, 0x75, 0xa3,
		0xb6, 0x49, 0x6a, 0xe1, 0x67, 0xaa, 0x72, 0x82, 0xd4, 0xe4, 0x9d, 0xed, 0x83, 0xaa, 0xa6, 0x1e,
		0xee, 0x1d, 0x6c, 0xef, 0x56, 0xe5, 0xe4, 0x4b, 0xb9, 0xec, 0x77, 0x26, 0xe5, 0x07, 0x0f, 0x1e,
		0x3c, 0x48, 0x2c, 0x7e, 0x3d, 0x01, 0xc5, 0xfe, 0x3e, 0x18, 0xfd, 0x28, 0x3c, 0x29, 0x0e, 0xad,
		0x1e, 0xf6, 0xb5, 0x37, 0x4c, 0x97, 0x86, 0x73, 0x47, 0x67, 0x9d, 0x64, 0xb0, 0x12, 0x73, 0xdc,
		0xaa, 0x8e, 0xfd, 0x4f, 0x9b, 0x2e, 0x09, 0xd6, 0x8e, 0xee, 0xa3, 0x1d, 0xb8, 0x60, 0x3b, 0x9a,
		0xe7, 0xeb, 0x76, 0x53, 0x77, 0x9b, 0x5a, 0x78, 0x5d, 0xa0, 0xe9, 0x86, 0x81, 0x3d, 0xcf, 0x61,
		0x95, 0x24, 0x60, 0x79, 0xda, 0x76, 0xea, 0xdc, 0x38, 0x4c, 0xb1, 0x15, 0x6e, 0x3a, 0x10, 0x35,
		0xc9, 0xd3, 0xa2, 0xe6, 0x29, 0xc8, 0x75, 0xf4, 0xae, 0x86, 0x6d, 0xdf, 0x3d, 0xa6, 0xdd, 0x5b,
		0x56, 0xcd, 0x76, 0xf4, 0x6e, 0x95, 0x3c, 0xff, 0xe0, 0xd6, 0x20, 0xea, 0xc7, 0x6f, 0x25, 0xa1,
		0x10, 0xed, 0xe0, 0x48, 0x43, 0x6c, 0xd0, 0x34, 0x2f, 0xd1, 0x2c, 0xf0, 0xec, 0x63, 0xfb, 0xbd,
		0xe5, 0x0d, 0x92, 0xff, 0xcb, 0x19, 0xd6, 0x57, 0xa9, 0x0c, 0x49, 0x6a, 0x2f, 0x89, 0x35, 0xcc,
		0xba, 0xf5, 0xac, 0xca, 0x9f, 0xd0, 0x16, 0x64, 0xee, 0x7a, 0x94, 0x3b, 0x43, 0xb9, 0x9f, 0x7b,
		0x3c, 0xf7, 0x6b, 0x75, 0x4a, 0x9e, 0x7b, 0xad, 0xae, 0xed, 0xd5, 0xd4, 0xdd, 0xca, 0x8e, 0xca,
		0xe1, 0xe8, 0x3c, 0xa4, 0x2c, 0xfd, 0xad, 0xe3, 0xfe, 0x4a, 0x41, 0x45, 0xe3, 0x3a, 0xfe, 0x3c,
		0xa4, 0xde, 0xc0, 0xfa, 0xbd, 0xfe, 0xfc, 0x4c, 0x45, 0x3f, 0xc0, 0xd0, 0xbf, 0x04, 0x69, 0xea,
		0x2f, 0x04, 0xc0, 0x3d, 0x26, 0x4f, 0xa0, 0x2c, 0xa4, 0x36, 0x6a, 0x2a, 0x09, 0x7f, 0x19, 0x0a,
		0x4c, 0xaa, 0xed, 0x6f, 0x57, 0x37, 0xaa, 0x72, 0x62, 0x71, 0x0d, 0x32, 0xcc, 0x09, 0x64, 0x6b,
		0x04, 0x6e, 0x90, 0x27, 0xf8, 0x23, 0xe7, 0x90, 0x84, 0xf6, 0x70, 0x77, 0xbd, 0xaa, 0xca, 0x89,
		0xe8, 0xf2, 0xfe, 0x95, 0x04, 0xf9, 0x48, 0x43, 0x45, 0x4a, 0xb9, 0x6e, 0x59, 0xce, 0x1b, 0x9a,
		0x6e, 0x99, 0xba, 0xc7, 0xd7, 0x07, 0xa8, 0xa8, 0x42, 0x24, 0xe3, 0xfa, 0xef, 0xff, 0x24, 0x36,
		0xbf, 0x28, 0x81, 0x3c, 0xd8, 0x8c, 0x0d, 0x0c, 0x50, 0xfa, 0xa1, 0x0e, 0xf0, 0x3d, 0x09, 0x8a,
		0xfd, 0x1d, 0xd8, 0xc0, 0xf0, 0x2e, 0xfe, 0x50, 0x87, 0xf7, 0x79, 0x09, 0xa6, 0xfa, 0xfa, 0xae,
		0xff, 0x57, 0xa3, 0x7b, 0x37, 0x09, 0xb3, 0x23, 0x70, 0xa8, 0xc2, 0x1b, 0x54, 0xd6, 0x33, 0x7f,
		0x7c, 0x9c, 0x77, 0x2d, 0x93, 0xfa, 0xb7, 0xaf, 0xbb, 0x3e, 0xef, 0x67, 0x5f, 0x04, 0xd9, 0x6c,
		0x62, 0xdb, 0x37, 0x5b, 0x26, 0x76, 0xf9, 0xd9, 0x98, 0x75, 0xad, 0xd3, 0xa1, 0x9c, 0x1d, 0x8f,
		0x7f, 0x04, 0x50, 0xd7, 0xf1, 0x4c, 0xdf, 0xbc, 0x8f, 0x35, 0xd3, 0x16, 0x07, 0x69, 0xd2, 0xc5,
		0xa6, 0x54, 0x59, 0x68, 0xb6, 0x6d, 0x3f, 0xb0, 0xb6, 0x71, 0x5b, 0x1f, 0xb0, 0x26, 0x69, 0x28,
		0xa9, 0xca, 0x42, 0x13, 0x58, 0x5f, 0x84, 0x42, 0xd3, 0xe9, 0x91, 0x86, 0x80, 0xd9, 0x91, 0xac,
		0x27, 0xa9, 0x79, 0x26, 0x0b, 0x4c, 0x78, 0xc7, 0x16, 0x9e, 0xe0, 0x0b, 0x6a, 0x9e, 0xc9, 0x98,
		0xc9, 0x0b, 0x30, 0xad, 0xb7, 0xdb, 0x2e, 0x21, 0x17, 0x44, 0xac, 0x0d, 0x2d, 0x06, 0x62, 0x6a,
		0x38, 0xff, 0x1a, 0x64, 0x85, 0x1f, 0x48, 0x61, 0x21, 0x9e, 0xd0, 0xba, 0xec, 0x1e, 0x25, 0x41,
		0x0e, 0xf5, 0xb6, 0x50, 0x5e, 0x84, 0x82, 0xe9, 0x69, 0xe1, 0x85, 0x5e, 0x62, 0x21, 0xb1, 0x94,
		0x55, 0xf3, 0xa6, 0x17, 0xdc, 0xe0, 0x2c, 0xbe, 0x9f, 0x80, 0x62, 0xff, 0x85, 0x24, 0xda, 0x84,
		0xac, 0xe5, 0x18, 0x3a, 0x0d, 0x04, 0x76, 0x1b, 0xbe, 0x14, 0x73, 0x87, 0xb9, 0xbc, 0xc3, 0xed,
		0xd5, 0x00, 0x39, 0xff, 0xf7, 0x12, 0x64, 0x85, 0x18, 0x9d, 0x83, 0x54, 0x57, 0xf7, 0x8f, 0x28,
		0x5d, 0x7a, 0x3d, 0x21, 0x4b, 0x2a, 0x7d, 0x26, 0x72, 0xaf, 0xab, 0xdb, 0x34, 0x04, 0xb8, 0x9c,
		0x3c, 0x93, 0x75, 0xb5, 0xb0, 0xde, 0xa4, 0x0d, 0xae, 0xd3, 0xe9, 0x60, 0xdb, 0xf7, 0xc4, 0xba,
		0x72, 0xf9, 0x06, 0x17, 0xa3, 0x97, 0x61, 0xc6, 0x77, 0x75, 0xd3, 0xea, 0xb3, 0x4d, 0x51, 0x5b,
		0x59, 0x28, 0x02, 0xe3, 0x32, 0x9c, 0x17, 0xbc, 0x4d, 0xec, 0xeb, 0xc6, 0x11, 0x6e, 0x86, 0xa0,
		0x0c, 0xbd, 0xed, 0x7a, 0x92, 0x1b, 0x6c, 0x72, 0xbd, 0xc0, 0xae, 0xdf, 0x81, 0x59, 0xc3, 0xe9,
		0x0c, 0x7a, 0x62, 0x5d, 0x1e, 0x38, 0x77, 0x79, 0xb7, 0xa5, 0xcf, 0x40, 0xd8, 0x54, 0x7c, 0x29,
		0x91, 0xdc, 0xda, 0x5f, 0xff, 0x4a, 0x62, 0x7e, 0x8b, 0xe1, 0xf6, 0x85, 0x07, 0x55, 0xdc, 0xb2,
		0xb0, 0x41, 0xbc, 0x03, 0xbf, 0xfd, 0x2c, 0x5c, 0x6e, 0x9b, 0xfe, 0x51, 0xaf, 0xb1, 0x6c, 0x38,
		0x9d, 0x4b, 0x1d, 0xbd, 0x69, 0xfa, 0xc7, 0x7a, 0xf8, 0x45, 0xa3, 0xed, 0xb4, 0x1d, 0xfa, 0x40,
		0xff, 0xe3, 0x5f, 0x35, 0x72, 0x81, 0x74, 0x3e, 0xf6, 0x13, 0x48, 0x79, 0x0f, 0x66, 0xb9, 0xb1,
		0x46, 0xaf, 0x55, 0x59, 0x17, 0x8a, 0x1e, 0x7b, 0x26, 0x57, 0xbe, 0xf6, 0x01, 0xad, 0x0a, 0xea,
		0x0c, 0x87, 0x12, 0x1d, 0xeb, 0x53, 0xcb, 0x2a, 0x3c, 0xd1, 0xc7, 0xc7, 0xc2, 0x18, 0xbb, 0x31,
		0x8c, 0x5f, 0xe7, 0x8c, 0xb3, 0x11, 0xc6, 0x3a, 0x87, 0x96, 0x37, 0x60, 0xea, 0x2c, 0x5c, 0x7f,
		0xcb, 0xb9, 0x0a, 0x38, 0x4a, 0xb2, 0x05, 0xd3, 0x94, 0xc4, 0xe8, 0x79, 0xbe, 0xd3, 0xa1, 0x39,
		0xe2, 0xf1, 0x34, 0x7f, 0xf7, 0x01, 0x8b, 0xab, 0x22, 0x81, 0x6d, 0x04, 0xa8, 0xf2, 0xa7, 0x60,
		0x8e, 0x48, 0xe8, 0x36, 0x8c, 0xb2, 0xc5, 0xdf, 0x22, 0x28, 0xff, 0xf0, 0x36, 0x0b, 0xbf, 0xd9,
		0x80, 0x20, 0xc2, 0x1b, 0x59, 0x89, 0x36, 0xf6, 0x7d, 0xec, 0x7a, 0x9a, 0x6e, 0x59, 0xe8, 0xb1,
		0x9f, 0x19, 0x94, 0x77, 0xbe, 0xdb, 0xbf, 0x12, 0x5b, 0x0c, 0x59, 0xb1, 0xac, 0xf2, 0x21, 0x3c,
		0x39, 0x62, 0x65, 0xc7, 0xe0, 0x7c, 0x97, 0x73, 0xce, 0x0d, 0xad, 0x2e, 0xa1, 0xdd, 0x07, 0x21,
		0x0f, 0xd6, 0x63, 0x0c, 0xce, 0xcf, 0x73, 0x4e, 0xc4, 0xb1, 0x62, 0x59, 0x08, 0xe3, 0x6b, 0x30,
		0x73, 0x1f, 0xbb, 0x0d, 0xc7, 0xe3, 0x47, 0xdf, 0x31, 0xe8, 0xde, 0xe3, 0x74, 0xd3, 0x1c, 0x48,
		0x0f, 0xc2, 0x84, 0xeb, 0x26, 0x64, 0x5b, 0xba, 0x81, 0xc7, 0xa0, 0xf8, 0x02, 0xa7, 0x98, 0x24,
		0xf6, 0x04, 0x5a, 0x81, 0x42, 0xdb, 0xe1, 0x99, 0x38, 0x1e, 0xfe, 0x45, 0x0e, 0xcf, 0x0b, 0x0c,
		0xa7, 0xe8, 0x3a, 0xdd, 0x9e, 0x45, 0xd2, 0x74, 0x3c, 0xc5, 0x6f, 0x08, 0x0a, 0x81, 0xe1, 0x14,
		0x67, 0x70, 0xeb, 0x6f, 0x0a, 0x0a, 0x2f, 0xe2, 0xcf, 0x57, 0x20, 0xef, 0xd8, 0xd6, 0xb1, 0x63,
		0x8f, 0x33, 0x88, 0xdf, 0xe2, 0x0c, 0xc0, 0x21, 0x84, 0xe0, 0x16, 0xe4, 0xc6, 0x5d, 0x88, 0xdf,
		0xe1, 0xf0, 0x2c, 0x16, 0x2b, 0xb0, 0x05, 0xd3, 0x22, 0xc9, 0x98, 0x8e, 0x3d, 0x06, 0xc5, 0xef,
		0x72, 0x8a, 0x62, 0x04, 0xc6, 0xa7, 0xe1, 0x63, 0xcf, 0x6f, 0xe3, 0x71, 0x48, 0xde, 0x17, 0xd3,
		0xe0, 0x10, 0xee, 0xca, 0x06, 0xb6, 0x8d, 0xa3, 0xf1, 0x18, 0xbe, 0x2c, 0x5c, 0x29, 0x30, 0x84,
		0x62, 0x03, 0xa6, 0x3a, 0xba, 0xeb, 0x1d, 0xe9, 0xd6, 0x58, 0xcb, 0xf1, 0x7b, 0x9c, 0xa3, 0x10,
		0x80, 0xb8, 0x47, 0x7a, 0xf6, 0x59, 0x68, 0xbe, 0x22, 0x3c, 0x12, 0x81, 0xf1, 0xad, 0xe7, 0xf9,
		0xf4, 0x76, 0xe1, 0x2c, 0x6c, 0xbf, 0x2f, 0xb6, 0x1e, 0xc3, 0xee, 0x46, 0x19, 0x6f, 0x41, 0xce,
		0x33, 0xdf, 0x1a, 0x8b, 0xe6, 0x0f, 0xc4, 0x4a, 0x53, 0x00, 0x01, 0xbf, 0x0e, 0xe7, 0x47, 0xa6,
		0xfa, 0x31, 0xc8, 0xfe, 0x90, 0x93, 0x9d, 0x1b, 0x91, 0xee, 0x79, 0x4a, 0x38, 0x2b, 0xe5, 0x1f,
		0x89, 0x94, 0x80, 0x07, 0xb8, 0xf6, 0x49, 0x27, 0xeb, 0xe9, 0xad, 0xb3, 0x79, 0xed, 0x8f, 0x85,
		0xd7, 0x18, 0xb6, 0xcf, 0x6b, 0x07, 0x70, 0x8e, 0x33, 0x9e, 0x6d, 0x5d, 0xbf, 0x2a, 0x12, 0x2b,
		0x43, 0x1f, 0xf6, 0xaf, 0xee, 0x8f, 0xc3, 0x7c, 0xe0, 0x4e, 0xd1, 0x84, 0x79, 0x5a, 0x47, 0xef,
		0x8e, 0xc1, 0xfc, 0x35, 0xce, 0x2c, 0x32, 0x7e, 0xd0, 0xc5, 0x79, 0xbb, 0x7a, 0x97, 0x90, 0xdf,
		0x01, 0x45, 0x90, 0xf7, 0x6c, 0x17, 0x1b, 0x4e, 0xdb, 0x36, 0xdf, 0xc2, 0xcd, 0x31, 0xa8, 0xff,
		0x64, 0x60, 0xa9, 0x0e, 0x23, 0x70, 0xc2, 0xbc, 0x0d, 0x72, 0xd0, 0x6f, 0x68, 0x66, 0xa7, 0xeb,
		0xb8, 0x7e, 0x0c, 0xe3, 0x9f, 0x8a, 0x95, 0x0a, 0x70, 0xdb, 0x14, 0x56, 0xae, 0x42, 0x91, 0x3e,
		0x8e, 0x1b, 0x92, 0x7f, 0xc6, 0x89, 0xa6, 0x42, 0x14, 0x4f, 0x1c, 0x86, 0xd3, 0xe9, 0xea, 0xee,
		0x38, 0xf9, 0xef, 0xcf, 0x45, 0xe2, 0xe0, 0x10, 0x16, 0x7d, 0xd3, 0x03, 0x95, 0x18, 0xc5, 0x7d,
		0x81, 0x55, 0x7e, 0xf2, 0x11, 0xdf, 0xb3, 0xfd, 0x85, 0xb8, 0xbc, 0x43, 0xdc, 0xd3, 0x5f, 0x2e,
		0xe3, 0xc9, 0xde, 0x7e, 0x14, 0x78, 0xa8, 0xaf, 0x5a, 0x96, 0x5f, 0x85, 0xa9, 0xbe, 0x52, 0x19,
		0x4f, 0xf5, 0x53, 0x9c, 0xaa, 0x10, 0xad, 0x94, 0xe5, 0x35, 0x48, 0x91, 0xb2, 0x17, 0x0f, 0xff,
		0x69, 0x0e, 0xa7, 0xe6, 0xe5, 0x4f, 0x40, 0x56, 0x94, 0xbb, 0x78, 0xe8, 0xcf, 0x70, 0x68, 0x00,
		0x21, 0x70, 0x51, 0xea, 0xe2, 0xe1, 0x3f, 0x2b, 0xe0, 0x02, 0x42, 0xe0, 0xe3, 0xbb, 0xf0, 0xaf,
		0x7f, 0x2e, 0xc5, 0xd3, 0x95, 0xf0, 0xdd, 0x2d, 0x98, 0xe4, 0x35, 0x2e, 0x1e, 0xfd, 0x59, 0xfe,
		0x72, 0x81, 0x28, 0x5f, 0x87, 0xf4, 0x98, 0x0e, 0xff, 0x79, 0x0e, 0x65, 0xf6, 0xe5, 0x0d, 0xc8,
		0x47, 0xea, 0x5a, 0x3c, 0xfc, 0x17, 0x38, 0x3c, 0x8a, 0x22, 0x43, 0xe7, 0x75, 0x2d, 0x9e, 0xe0,
		0x17, 0xc5, 0xd0, 0x39, 0x82, 0xb8, 0x4d, 0x94, 0xb4, 0x78, 0xf4, 0x2f, 0x09, 0xaf, 0x0b, 0x48,
		0xf9, 0x15, 0xc8, 0x05, 0x69, 0x2a, 0x1e, 0xff, 0xcb, 0x1c, 0x1f, 0x62, 0x88, 0x07, 0x22, 0x69,
		0x32, 0x9e, 0xe2, 0x57, 0x84, 0x07, 0x22, 0x28, 0xb2, 0x8d, 0x06, 0x4b, 0x5f, 0x3c, 0xd3, 0xaf,
		0x8a, 0x6d, 0x34, 0x50, 0xf9, 0xc8, 0x6a, 0xd2, 0x6c, 0x11, 0x4f, 0xf1, 0x6b, 0x62, 0x35, 0xa9,
		0x3d, 0x19, 0xc6, 0x60, 0x2d, 0x89, 0xe7, 0xf8, 0x75, 0x31, 0x8c, 0x81, 0x52, 0x52, 0xde, 0x07,
		0x34, 0x5c, 0x47, 0xe2, 0xf9, 0x3e, 0xc7, 0xf9, 0x66, 0x86, 0xca, 0x48, 0xf9, 0xd3, 0x70, 0x6e,
		0x74, 0x0d, 0x89, 0x67, 0x7d, 0xe7, 0xd1, 0x40, 0xd7, 0x1f, 0x2d, 0x21, 0xe5, 0x83, 0xb0, 0xeb,
		0x8f, 0xd6, 0x8f, 0x78, 0xda, 0x77, 0x1f, 0xf5, 0x1f, 0xec, 0xa2, 0xe5, 0xa3, 0x5c, 0x01, 0x08,
		0x53, 0x77, 0x3c, 0xd7, 0x7b, 0x9c, 0x2b, 0x02, 0x22, 0x5b, 0x83, 0x67, 0xee, 0x78, 0xfc, 0x17,
		0xc4, 0xd6, 0xe0, 0x88, 0xf2, 0x2d, 0xc8, 0xda, 0x3d, 0xcb, 0x22, 0xc1, 0x81, 0x1e, 0xff, 0xab,
		0x06, 0xe5, 0x5f, 0x3f, 0xe2, 0x1b, 0x43, 0x00, 0xca, 0x6b, 0x90, 0xc6, 0x9d, 0x06, 0x6e, 0xc6,
		0x21, 0xff, 0xed, 0x23, 0x91, 0x10, 0x88, 0x75, 0xf9, 0x15, 0x00, 0x76, 0x68, 0xa4, 0xd7, 0xd8,
		0x31, 0xd8, 0x7f, 0xff, 0x88, 0x7f, 0x69, 0x0d, 0x21, 0x21, 0x01, 0xfb, 0x6e, 0xfb, 0x78, 0x82,
		0xef, 0xf6, 0x13, 0xd0, 0x83, 0xe6, 0x4d, 0x98, 0xbc, 0xeb, 0x39, 0xb6, 0xaf, 0xb7, 0xe3, 0xd0,
		0xff, 0xc1, 0xd1, 0xc2, 0x9e, 0x38, 0xac, 0xe3, 0xb8, 0xd8, 0xd7, 0xdb, 0x5e, 0x1c, 0xf6, 0x3f,
		0x39, 0x36, 0x00, 0x10, 0xb0, 0xa1, 0x7b, 0xfe, 0x38, 0xf3, 0xfe, 0x2f, 0x01, 0x16, 0x00, 0x32,
		0x68, 0xf2, 0xff, 0x3d, 0x7c, 0x1c, 0x87, 0xfd, 0x50, 0x0c, 0x9a, 0xdb, 0x97, 0x3f, 0x01, 0x39,
		0xf2, 0x2f, 0xfb, 0xf5, 0x41, 0x0c, 0xf8, 0xbf, 0x39, 0x38, 0x44, 0xac, 0x5f, 0x1c, 0x7d, 0xbb,
		0x03, 0x5b, 0xce, 0x96, 0xc3, 0xee, 0x75, 0xe0, 0x9d, 0x34, 0x28, 0x86, 0xd3, 0x69, 0x38, 0xde,
		0x25, 0x1b, 0x9b, 0xfe, 0x11, 0x76, 0x2f, 0x39, 0x36, 0xb7, 0x45, 0x49, 0xc7, 0xc6, 0xf3, 0x67,
		0xbe, 0xc5, 0x59, 0x3c, 0x0f, 0xe9, 0x7a, 0xaf, 0xd1, 0x38, 0x46, 0x32, 0x24, 0xbd, 0x5e, 0x83,
		0x7f, 0xa2, 0x26, 0xff, 0x2e, 0x7e, 0x2b, 0x09, 0xf9, 0xba, 0xde, 0xe9, 0x5a, 0xb8, 0x66, 0xe3,
		0x5a, 0x0b, 0x29, 0x90, 0xa1, 0x93, 0xb8, 0x42, 0x8d, 0xa4, 0xdb, 0x13, 0x6a, 0x86, 0xfe, 0x66,
		0xef, 0x4a, 0xa0, 0x59, 0xa1, 0xd7, 0xfc, 0x89, 0x40, 0xb3, 0x12, 0x68, 0xae, 0xb2, 0x1f, 0x43,
		0x05, 0x9a, 0xab, 0x81, 0x66, 0x95, 0xde, 0x95, 0x25, 0x03, 0xcd, 0x6a, 0xa0, 0x59, 0xa3, 0xd7,
		0x9d, 0x53, 0x81, 0x66, 0x2d, 0xd0, 0x5c, 0xa3, 0x17, 0x9c, 0xa9, 0x40, 0x73, 0x2d, 0xd0, 0x5c,
		0xa7, 0xf7, 0x9a, 0x33, 0x81, 0xe6, 0x7a, 0xa0, 0xb9, 0x41, 0xef, 0x32, 0x51, 0xa0, 0xb9, 0x11,
		0x68, 0x6e, 0xd2, 0xcf, 0xd0, 0x93, 0x81, 0xe6, 0x26, 0x9a, 0x87, 0x49, 0x36, 0xd3, 0xcb, 0xf4,
		0xb3, 0xcd, 0xf4, 0xed, 0x09, 0x75, 0x92, 0x4d, 0xf5, 0x72, 0xa8, 0xbb, 0x42, 0x3f, 0x35, 0x67,
		0x42, 0xdd, 0x95, 0x50, 0xb7, 0x42, 0x7f, 0x3a, 0x29, 0x87, 0xba, 0x95, 0x50, 0x77, 0x55, 0x99,
		0x22, 0x1b, 0x35, 0xd4, 0x5d, 0x0d, 0x75, 0xab, 0x4a, 0x91, 0xf8, 0x3f, 0xd4, 0xad, 0x86, 0xba,
		0x35, 0x65, 0x7a, 0x41, 0x5a, 0x2a, 0x84, 0xba, 0x35, 0xf4, 0x71, 0xc8, 0x7b, 0xbd, 0x86, 0xc6,
		0xbf, 0x32, 0xd2, 0x4f, 0xda, 0xf9, 0x15, 0x58, 0x26, 0x41, 0x41, 0x17, 0xf5, 0xf6, 0x84, 0x0a,
		0x5e, 0xaf, 0xc1, 0xf3, 0xd3, 0x7a, 0x01, 0xe8, 0xb9, 0x55, 0xa3, 0x3f, 0xc9, 0x5a, 0xdf, 0xfc,
		0xc6, 0xc3, 0xd2, 0xc4, 0x37, 0x1f, 0x96, 0x26, 0xfe, 0xe9, 0x61, 0x69, 0xe2, 0xdb, 0x0f, 0x4b,
		0xd2, 0x87, 0x0f, 0x4b, 0xd2, 0xf7, 0x1e, 0x96, 0xa4, 0x07, 0x27, 0x25, 0xe9, 0xcb, 0x27, 0x25,
		0xe9, 0xab, 0x27, 0x25, 0xe9, 0x2f, 0x4f, 0x4a, 0xd2, 0x37, 0x4e, 0x4a, 0x13, 0xdf, 0x3c, 0x29,
		0x4d, 0x7c, 0xfb, 0xa4, 0x24, 0x7d, 0xe7, 0xa4, 0x34, 0xf1, 0xe1, 0x49, 0x49, 0xfa, 0xde, 0x49,
		0x69, 0xe2, 0xc1, 0x3f, 0x97, 0x26, 0x1a, 0x19, 0x1a, 0x46, 0x57, 0xff, 0x37, 0x00, 0x00, 0xff,
		0xff, 0x43, 0xde, 0x31, 0xe4, 0x09, 0x2d, 0x00, 0x00,
	}
	r := bytes.NewReader(gzipped)
	gzipr, err := compress_gzip.NewReader(r)
	if err != nil {
		panic(err)
	}
	ungzipped, err := io_ioutil.ReadAll(gzipr)
	if err != nil {
		panic(err)
	}
	if err := github_com_maditya_protobuf_proto.Unmarshal(ungzipped, d); err != nil {
		panic(err)
	}
	return d
}
func (this *Subby) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Subby")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Subby but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Subby but is not nil && this == nil")
	}
	if this.Sub != that1.Sub {
		return fmt.Errorf("Sub this(%v) Not Equal that(%v)", this.Sub, that1.Sub)
	}
	return nil
}
func (this *Subby) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Sub != that1.Sub {
		return false
	}
	return true
}
func (this *SampleOneOf) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf but is not nil && this == nil")
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return fmt.Errorf("this.TestOneof != nil && that1.TestOneof == nil")
		}
	} else if this.TestOneof == nil {
		return fmt.Errorf("this.TestOneof == nil && that1.TestOneof != nil")
	} else if err := this.TestOneof.VerboseEqual(that1.TestOneof); err != nil {
		return err
	}
	return nil
}
func (this *SampleOneOf_Field1) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field1")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field1 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field1 but is not nil && this == nil")
	}
	if this.Field1 != that1.Field1 {
		return fmt.Errorf("Field1 this(%v) Not Equal that(%v)", this.Field1, that1.Field1)
	}
	return nil
}
func (this *SampleOneOf_Field2) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field2")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field2 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field2 but is not nil && this == nil")
	}
	if this.Field2 != that1.Field2 {
		return fmt.Errorf("Field2 this(%v) Not Equal that(%v)", this.Field2, that1.Field2)
	}
	return nil
}
func (this *SampleOneOf_Field3) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field3")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field3 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field3 but is not nil && this == nil")
	}
	if this.Field3 != that1.Field3 {
		return fmt.Errorf("Field3 this(%v) Not Equal that(%v)", this.Field3, that1.Field3)
	}
	return nil
}
func (this *SampleOneOf_Field4) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field4")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field4 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field4 but is not nil && this == nil")
	}
	if this.Field4 != that1.Field4 {
		return fmt.Errorf("Field4 this(%v) Not Equal that(%v)", this.Field4, that1.Field4)
	}
	return nil
}
func (this *SampleOneOf_Field5) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field5")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field5 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field5 but is not nil && this == nil")
	}
	if this.Field5 != that1.Field5 {
		return fmt.Errorf("Field5 this(%v) Not Equal that(%v)", this.Field5, that1.Field5)
	}
	return nil
}
func (this *SampleOneOf_Field6) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field6")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field6 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field6 but is not nil && this == nil")
	}
	if this.Field6 != that1.Field6 {
		return fmt.Errorf("Field6 this(%v) Not Equal that(%v)", this.Field6, that1.Field6)
	}
	return nil
}
func (this *SampleOneOf_Field7) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field7")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field7 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field7 but is not nil && this == nil")
	}
	if this.Field7 != that1.Field7 {
		return fmt.Errorf("Field7 this(%v) Not Equal that(%v)", this.Field7, that1.Field7)
	}
	return nil
}
func (this *SampleOneOf_Field8) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field8")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field8 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field8 but is not nil && this == nil")
	}
	if this.Field8 != that1.Field8 {
		return fmt.Errorf("Field8 this(%v) Not Equal that(%v)", this.Field8, that1.Field8)
	}
	return nil
}
func (this *SampleOneOf_Field9) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field9")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field9 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field9 but is not nil && this == nil")
	}
	if this.Field9 != that1.Field9 {
		return fmt.Errorf("Field9 this(%v) Not Equal that(%v)", this.Field9, that1.Field9)
	}
	return nil
}
func (this *SampleOneOf_Field10) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field10")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field10 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field10 but is not nil && this == nil")
	}
	if this.Field10 != that1.Field10 {
		return fmt.Errorf("Field10 this(%v) Not Equal that(%v)", this.Field10, that1.Field10)
	}
	return nil
}
func (this *SampleOneOf_Field11) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field11")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field11 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field11 but is not nil && this == nil")
	}
	if this.Field11 != that1.Field11 {
		return fmt.Errorf("Field11 this(%v) Not Equal that(%v)", this.Field11, that1.Field11)
	}
	return nil
}
func (this *SampleOneOf_Field12) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field12")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field12 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field12 but is not nil && this == nil")
	}
	if this.Field12 != that1.Field12 {
		return fmt.Errorf("Field12 this(%v) Not Equal that(%v)", this.Field12, that1.Field12)
	}
	return nil
}
func (this *SampleOneOf_Field13) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field13")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field13 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field13 but is not nil && this == nil")
	}
	if this.Field13 != that1.Field13 {
		return fmt.Errorf("Field13 this(%v) Not Equal that(%v)", this.Field13, that1.Field13)
	}
	return nil
}
func (this *SampleOneOf_Field14) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field14")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field14 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field14 but is not nil && this == nil")
	}
	if this.Field14 != that1.Field14 {
		return fmt.Errorf("Field14 this(%v) Not Equal that(%v)", this.Field14, that1.Field14)
	}
	return nil
}
func (this *SampleOneOf_Field15) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field15")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field15 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field15 but is not nil && this == nil")
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return fmt.Errorf("Field15 this(%v) Not Equal that(%v)", this.Field15, that1.Field15)
	}
	return nil
}
func (this *SampleOneOf_SubMessage) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_SubMessage")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_SubMessage but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_SubMessage but is not nil && this == nil")
	}
	if !this.SubMessage.Equal(that1.SubMessage) {
		return fmt.Errorf("SubMessage this(%v) Not Equal that(%v)", this.SubMessage, that1.SubMessage)
	}
	return nil
}
func (this *SampleOneOf) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return false
		}
	} else if this.TestOneof == nil {
		return false
	} else if !this.TestOneof.Equal(that1.TestOneof) {
		return false
	}
	return true
}
func (this *SampleOneOf_Field1) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field1 != that1.Field1 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field2) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field2 != that1.Field2 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field3) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field3 != that1.Field3 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field4) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field4 != that1.Field4 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field5) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field5 != that1.Field5 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field6) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field6 != that1.Field6 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field7) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field7 != that1.Field7 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field8) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field8 != that1.Field8 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field9) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field9 != that1.Field9 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field10) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field10 != that1.Field10 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field11) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field11 != that1.Field11 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field12) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field12 != that1.Field12 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field13) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field13 != that1.Field13 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field14) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field14 != that1.Field14 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field15) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func (this *SampleOneOf_SubMessage) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.SubMessage.Equal(that1.SubMessage) {
		return false
	}
	return true
}
func (this *Subby) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&one.Subby{")
	s = append(s, "Sub: "+fmt.Sprintf("%#v", this.Sub)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SampleOneOf) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 20)
	s = append(s, "&one.SampleOneOf{")
	if this.TestOneof != nil {
		s = append(s, "TestOneof: "+fmt.Sprintf("%#v", this.TestOneof)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SampleOneOf_Field1) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field1{` +
		`Field1:` + fmt.Sprintf("%#v", this.Field1) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field2{` +
		`Field2:` + fmt.Sprintf("%#v", this.Field2) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field3) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field3{` +
		`Field3:` + fmt.Sprintf("%#v", this.Field3) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field4) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field4{` +
		`Field4:` + fmt.Sprintf("%#v", this.Field4) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field5) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field5{` +
		`Field5:` + fmt.Sprintf("%#v", this.Field5) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field6) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field6{` +
		`Field6:` + fmt.Sprintf("%#v", this.Field6) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field7) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field7{` +
		`Field7:` + fmt.Sprintf("%#v", this.Field7) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field8) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field8{` +
		`Field8:` + fmt.Sprintf("%#v", this.Field8) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field9) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field9{` +
		`Field9:` + fmt.Sprintf("%#v", this.Field9) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field10) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field10{` +
		`Field10:` + fmt.Sprintf("%#v", this.Field10) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field11) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field11{` +
		`Field11:` + fmt.Sprintf("%#v", this.Field11) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field12) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field12{` +
		`Field12:` + fmt.Sprintf("%#v", this.Field12) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field13) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field13{` +
		`Field13:` + fmt.Sprintf("%#v", this.Field13) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field14) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field14{` +
		`Field14:` + fmt.Sprintf("%#v", this.Field14) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field15) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field15{` +
		`Field15:` + fmt.Sprintf("%#v", this.Field15) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_SubMessage) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_SubMessage{` +
		`SubMessage:` + fmt.Sprintf("%#v", this.SubMessage) + `}`}, ", ")
	return s
}
func valueToGoStringOne(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func extensionToGoStringOne(m github_com_maditya_protobuf_proto.Message) string {
	e := github_com_maditya_protobuf_proto.GetUnsafeExtensionsMap(m)
	if e == nil {
		return "nil"
	}
	s := "proto.NewUnsafeXXX_InternalExtensions(map[int32]proto.Extension{"
	keys := make([]int, 0, len(e))
	for k := range e {
		keys = append(keys, int(k))
	}
	sort.Ints(keys)
	ss := []string{}
	for _, k := range keys {
		ss = append(ss, strconv.Itoa(k)+": "+e[int32(k)].GoString())
	}
	s += strings.Join(ss, ",") + "})"
	return s
}
func NewPopulatedSubby(r randyOne, easy bool) *Subby {
	this := &Subby{}
	this.Sub = randStringOne(r)
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSampleOneOf(r randyOne, easy bool) *SampleOneOf {
	this := &SampleOneOf{}
	oneofNumber_TestOneof := []int32{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}[r.Intn(16)]
	switch oneofNumber_TestOneof {
	case 1:
		this.TestOneof = NewPopulatedSampleOneOf_Field1(r, easy)
	case 2:
		this.TestOneof = NewPopulatedSampleOneOf_Field2(r, easy)
	case 3:
		this.TestOneof = NewPopulatedSampleOneOf_Field3(r, easy)
	case 4:
		this.TestOneof = NewPopulatedSampleOneOf_Field4(r, easy)
	case 5:
		this.TestOneof = NewPopulatedSampleOneOf_Field5(r, easy)
	case 6:
		this.TestOneof = NewPopulatedSampleOneOf_Field6(r, easy)
	case 7:
		this.TestOneof = NewPopulatedSampleOneOf_Field7(r, easy)
	case 8:
		this.TestOneof = NewPopulatedSampleOneOf_Field8(r, easy)
	case 9:
		this.TestOneof = NewPopulatedSampleOneOf_Field9(r, easy)
	case 10:
		this.TestOneof = NewPopulatedSampleOneOf_Field10(r, easy)
	case 11:
		this.TestOneof = NewPopulatedSampleOneOf_Field11(r, easy)
	case 12:
		this.TestOneof = NewPopulatedSampleOneOf_Field12(r, easy)
	case 13:
		this.TestOneof = NewPopulatedSampleOneOf_Field13(r, easy)
	case 14:
		this.TestOneof = NewPopulatedSampleOneOf_Field14(r, easy)
	case 15:
		this.TestOneof = NewPopulatedSampleOneOf_Field15(r, easy)
	case 16:
		this.TestOneof = NewPopulatedSampleOneOf_SubMessage(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSampleOneOf_Field1(r randyOne, easy bool) *SampleOneOf_Field1 {
	this := &SampleOneOf_Field1{}
	this.Field1 = float64(r.Float64())
	if r.Intn(2) == 0 {
		this.Field1 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field2(r randyOne, easy bool) *SampleOneOf_Field2 {
	this := &SampleOneOf_Field2{}
	this.Field2 = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Field2 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field3(r randyOne, easy bool) *SampleOneOf_Field3 {
	this := &SampleOneOf_Field3{}
	this.Field3 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field3 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field4(r randyOne, easy bool) *SampleOneOf_Field4 {
	this := &SampleOneOf_Field4{}
	this.Field4 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field4 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field5(r randyOne, easy bool) *SampleOneOf_Field5 {
	this := &SampleOneOf_Field5{}
	this.Field5 = uint32(r.Uint32())
	return this
}
func NewPopulatedSampleOneOf_Field6(r randyOne, easy bool) *SampleOneOf_Field6 {
	this := &SampleOneOf_Field6{}
	this.Field6 = uint64(uint64(r.Uint32()))
	return this
}
func NewPopulatedSampleOneOf_Field7(r randyOne, easy bool) *SampleOneOf_Field7 {
	this := &SampleOneOf_Field7{}
	this.Field7 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field7 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field8(r randyOne, easy bool) *SampleOneOf_Field8 {
	this := &SampleOneOf_Field8{}
	this.Field8 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field8 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field9(r randyOne, easy bool) *SampleOneOf_Field9 {
	this := &SampleOneOf_Field9{}
	this.Field9 = uint32(r.Uint32())
	return this
}
func NewPopulatedSampleOneOf_Field10(r randyOne, easy bool) *SampleOneOf_Field10 {
	this := &SampleOneOf_Field10{}
	this.Field10 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field10 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field11(r randyOne, easy bool) *SampleOneOf_Field11 {
	this := &SampleOneOf_Field11{}
	this.Field11 = uint64(uint64(r.Uint32()))
	return this
}
func NewPopulatedSampleOneOf_Field12(r randyOne, easy bool) *SampleOneOf_Field12 {
	this := &SampleOneOf_Field12{}
	this.Field12 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field12 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field13(r randyOne, easy bool) *SampleOneOf_Field13 {
	this := &SampleOneOf_Field13{}
	this.Field13 = bool(bool(r.Intn(2) == 0))
	return this
}
func NewPopulatedSampleOneOf_Field14(r randyOne, easy bool) *SampleOneOf_Field14 {
	this := &SampleOneOf_Field14{}
	this.Field14 = randStringOne(r)
	return this
}
func NewPopulatedSampleOneOf_Field15(r randyOne, easy bool) *SampleOneOf_Field15 {
	this := &SampleOneOf_Field15{}
	v1 := r.Intn(100)
	this.Field15 = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Field15[i] = byte(r.Intn(256))
	}
	return this
}
func NewPopulatedSampleOneOf_SubMessage(r randyOne, easy bool) *SampleOneOf_SubMessage {
	this := &SampleOneOf_SubMessage{}
	this.SubMessage = NewPopulatedSubby(r, easy)
	return this
}

type randyOne interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneOne(r randyOne) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringOne(r randyOne) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneOne(r)
	}
	return string(tmps)
}
func randUnrecognizedOne(r randyOne, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldOne(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldOne(data []byte, r randyOne, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateOne(data, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		data = encodeVarintPopulateOne(data, uint64(v3))
	case 1:
		data = encodeVarintPopulateOne(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateOne(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateOne(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateOne(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateOne(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
func (m *Subby) Size() (n int) {
	var l int
	_ = l
	l = len(m.Sub)
	if l > 0 {
		n += 1 + l + sovOne(uint64(l))
	}
	return n
}

func (m *SampleOneOf) Size() (n int) {
	var l int
	_ = l
	if m.TestOneof != nil {
		n += m.TestOneof.Size()
	}
	return n
}

func (m *SampleOneOf_Field1) Size() (n int) {
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field2) Size() (n int) {
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field3) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field3))
	return n
}
func (m *SampleOneOf_Field4) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field4))
	return n
}
func (m *SampleOneOf_Field5) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field5))
	return n
}
func (m *SampleOneOf_Field6) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field6))
	return n
}
func (m *SampleOneOf_Field7) Size() (n int) {
	var l int
	_ = l
	n += 1 + sozOne(uint64(m.Field7))
	return n
}
func (m *SampleOneOf_Field8) Size() (n int) {
	var l int
	_ = l
	n += 1 + sozOne(uint64(m.Field8))
	return n
}
func (m *SampleOneOf_Field9) Size() (n int) {
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field10) Size() (n int) {
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field11) Size() (n int) {
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field12) Size() (n int) {
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field13) Size() (n int) {
	var l int
	_ = l
	n += 2
	return n
}
func (m *SampleOneOf_Field14) Size() (n int) {
	var l int
	_ = l
	l = len(m.Field14)
	n += 1 + l + sovOne(uint64(l))
	return n
}
func (m *SampleOneOf_Field15) Size() (n int) {
	var l int
	_ = l
	if m.Field15 != nil {
		l = len(m.Field15)
		n += 1 + l + sovOne(uint64(l))
	}
	return n
}
func (m *SampleOneOf_SubMessage) Size() (n int) {
	var l int
	_ = l
	if m.SubMessage != nil {
		l = m.SubMessage.Size()
		n += 2 + l + sovOne(uint64(l))
	}
	return n
}

func sovOne(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOne(x uint64) (n int) {
	return sovOne(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Subby) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Subby{`,
		`Sub:` + fmt.Sprintf("%v", this.Sub) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf{`,
		`TestOneof:` + fmt.Sprintf("%v", this.TestOneof) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field1) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field1{`,
		`Field1:` + fmt.Sprintf("%v", this.Field1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field2{`,
		`Field2:` + fmt.Sprintf("%v", this.Field2) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field3) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field3{`,
		`Field3:` + fmt.Sprintf("%v", this.Field3) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field4) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field4{`,
		`Field4:` + fmt.Sprintf("%v", this.Field4) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field5) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field5{`,
		`Field5:` + fmt.Sprintf("%v", this.Field5) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field6) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field6{`,
		`Field6:` + fmt.Sprintf("%v", this.Field6) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field7) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field7{`,
		`Field7:` + fmt.Sprintf("%v", this.Field7) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field8) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field8{`,
		`Field8:` + fmt.Sprintf("%v", this.Field8) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field9) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field9{`,
		`Field9:` + fmt.Sprintf("%v", this.Field9) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field10) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field10{`,
		`Field10:` + fmt.Sprintf("%v", this.Field10) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field11) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field11{`,
		`Field11:` + fmt.Sprintf("%v", this.Field11) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field12) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field12{`,
		`Field12:` + fmt.Sprintf("%v", this.Field12) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field13) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field13{`,
		`Field13:` + fmt.Sprintf("%v", this.Field13) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field14) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field14{`,
		`Field14:` + fmt.Sprintf("%v", this.Field14) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field15) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field15{`,
		`Field15:` + fmt.Sprintf("%v", this.Field15) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_SubMessage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_SubMessage{`,
		`SubMessage:` + strings.Replace(fmt.Sprintf("%v", this.SubMessage), "Subby", "Subby", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringOne(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}

func init() { proto.RegisterFile("combos/neither/one.proto", fileDescriptorOne) }

var fileDescriptorOne = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xd2, 0xbf, 0x6e, 0xdb, 0x30,
	0x10, 0x06, 0x70, 0x5e, 0x14, 0xcb, 0x09, 0xed, 0x34, 0xae, 0xa6, 0x6b, 0x86, 0x03, 0x91, 0x89,
	0x4b, 0x2d, 0x5b, 0xb2, 0xf3, 0x67, 0x0d, 0x8a, 0xc2, 0x4b, 0x11, 0xc0, 0x79, 0x80, 0xc0, 0x4c,
	0x68, 0xc7, 0x40, 0x24, 0x06, 0x91, 0x34, 0x64, 0xcb, 0xe3, 0x74, 0xec, 0xd8, 0x47, 0xc8, 0x98,
	0xb1, 0x43, 0x87, 0x88, 0x5d, 0x3a, 0x66, 0xf4, 0x18, 0x58, 0x02, 0xc8, 0xed, 0x0e, 0x3f, 0x72,
	0xf8, 0xc8, 0x8f, 0xe3, 0x8d, 0xc9, 0x94, 0x29, 0xe2, 0x5c, 0xaf, 0xcb, 0x3b, 0xfd, 0x18, 0x9b,
	0x5c, 0x0f, 0x1f, 0x1e, 0x4d, 0x69, 0xa2, 0xc0, 0xe4, 0xfa, 0x68, 0xb4, 0x5a, 0x97, 0x77, 0x95,
	0x1a, 0xde, 0x98, 0x2c, 0xce, 0x16, 0xb7, 0xeb, 0xf2, 0x69, 0x11, 0x37, 0xac, 0xaa, 0x65, 0xbc,
	0x32, 0x2b, 0xd3, 0x2c, 0xcd, 0xd4, 0x5e, 0x3b, 0xfe, 0xc2, 0x3b, 0x57, 0x95, 0x52, 0x4f, 0xd1,
	0x80, 0x07, 0x45, 0xa5, 0x10, 0x04, 0xc8, 0xfd, 0xf9, 0x76, 0x3c, 0xfe, 0x1b, 0xf0, 0xde, 0xd5,
	0x22, 0x7b, 0xb8, 0xd7, 0x97, 0xb9, 0xbe, 0x5c, 0x46, 0xc8, 0xc3, 0xef, 0x6b, 0x7d, 0x7f, 0x3b,
	0x6e, 0x0e, 0xc1, 0x8c, 0xcd, 0xc3, 0x65, 0xb3, 0x3b, 0x49, 0x70, 0x47, 0x80, 0xdc, 0x71, 0x92,
	0x38, 0x49, 0x31, 0x10, 0x20, 0x3b, 0x4e, 0x52, 0x27, 0x13, 0xdc, 0x15, 0x20, 0x03, 0x27, 0x13,
	0x27, 0x53, 0xec, 0x08, 0x90, 0x07, 0x4e, 0xa6, 0x4e, 0x4e, 0x30, 0x14, 0x20, 0x77, 0x9d, 0x9c,
	0x38, 0x39, 0xc5, 0xae, 0x00, 0xf9, 0xd9, 0xc9, 0xa9, 0x93, 0x33, 0xdc, 0x13, 0x20, 0x23, 0x27,
	0x67, 0x4e, 0xce, 0x71, 0x5f, 0x80, 0xec, 0x3a, 0x39, 0x8f, 0x8e, 0x78, 0xb7, 0x4d, 0x3a, 0x42,
	0x2e, 0x40, 0x1e, 0xce, 0xd8, 0xbc, 0xdb, 0x46, 0x1d, 0x79, 0x1b, 0x63, 0x4f, 0x80, 0x0c, 0xbd,
	0x8d, 0xbd, 0x25, 0xd8, 0x17, 0x20, 0x07, 0xde, 0x12, 0x6f, 0x29, 0x1e, 0x08, 0x90, 0x7b, 0xde,
	0x52, 0x6f, 0x13, 0xfc, 0xb4, 0x7d, 0x7f, 0x6f, 0x13, 0x6f, 0x53, 0x3c, 0x14, 0x20, 0xfb, 0xde,
	0xa6, 0xd1, 0x57, 0xde, 0x2b, 0x2a, 0x75, 0x9d, 0xe9, 0xa2, 0x58, 0xac, 0x34, 0x0e, 0x04, 0xc8,
	0x5e, 0xc2, 0x87, 0xdb, 0x52, 0x34, 0x9f, 0x3a, 0x63, 0x73, 0x5e, 0x54, 0xea, 0x47, 0xeb, 0x17,
	0x7d, 0xce, 0x4b, 0x5d, 0x94, 0xd7, 0x26, 0xd7, 0x66, 0x79, 0xf1, 0xed, 0xa5, 0x26, 0xf6, 0x5a,
	0x13, 0xfb, 0x53, 0x13, 0x7b, 0xab, 0x09, 0xde, 0x6b, 0x82, 0x4d, 0x4d, 0xf0, 0x6c, 0x09, 0x7e,
	0x5a, 0x82, 0x5f, 0x96, 0xe0, 0xb7, 0x25, 0x78, 0xb1, 0xc4, 0x5e, 0x2d, 0xb1, 0x37, 0x4b, 0xf0,
	0xdf, 0x12, 0x7b, 0xb7, 0x04, 0x1b, 0x4b, 0xec, 0xf9, 0x1f, 0x31, 0x15, 0x36, 0x35, 0x4a, 0x3f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x33, 0x01, 0xa9, 0x2f, 0x99, 0x02, 0x00, 0x00,
}
